services:
  compose-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "saasapi.apphost-17e8f64728-postgres-data"
        read_only: false
    networks:
      - "aspire"
  seq:
    image: "docker.io/datalust/seq:2025.2"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "True"
    expose:
      - "80"
    networks:
      - "aspire"
  sass-api:
    image: "${SASS_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${SASS_API_PORT}"
      ConnectionStrings__saasdb: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=saasdb"
      SAASDB_HOST: "postgres"
      SAASDB_PORT: "5432"
      SAASDB_USERNAME: "postgres"
      SAASDB_PASSWORD: "${POSTGRES_PASSWORD}"
      SAASDB_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/saasdb"
      SAASDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/saasdb"
      SAASDB_DATABASENAME: "saasdb"
      ConnectionStrings__seq: "http://seq:80"
      SEQ_HOST: "seq"
      SEQ_PORT: "80"
      SEQ_URI: "http://seq:80"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "sass-api"
    expose:
      - "${SASS_API_PORT}"
    depends_on:
      postgres:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  saasapi.apphost-17e8f64728-postgres-data:
    driver: "local"
