services:
  saas.api:
    image: ${DOCKER_REGISTRY-}saasapi
    container_name: Saas.Api
    build:
      context: .
      dockerfile: src/Api/Saas.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      - saas.database

  saas.database:
    image: postgres:18
    container_name: Saas.Database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saasdb
    volumes:
     - ./.containers/db:/var/lib/postgresql/18/docker
    ports:
      - 5432:5432
